//product items here//

let shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "MuscleBlaze Biozyme Whey",
    price: 4749,
    desc: "Performance Whey, 4.4lb Rich Choclate Powder",
    img: "images/products/product1.png",
  },
  {
    id: "ioytrhndcv",
    name: "MuscleBlaze Super Gainer XXL Powder",
    price: 3599,
    desc: "5 kg (11 lb), Chocolate",
    img: "images/products/product2.png",
  },
  {
    id: "wuefbncxbsn",
    name: "MB Fuel One Whey Protein Powder",
    price: 1749,
    desc: " Immunity+1 kg (2.2 lb), Chocolate",
    img: "images/products/product3.png",
  },
  {
    id: "thyfhcbcv",
    name: "HealthKart HK Vitals Super Strength Fish Oil",
    price: 599,
    desc: "Fish Oil Purity 84%, 60 softgels",
    img: "images/products/product4.png",
  },
  {
    id: "thiecbawdjksadjk",
    name: "MuscleBlaze Beginner's Protein Powders",
    price: 1239,
    desc: "1 kg (2.2 lb), Cookies and Cream",
    img: "images/products/product5.png",
  },
  {
    id: "iuertrywebncdjksadjk",
    name: "ONN Gold Standard Whey",
    price: 200,
    desc: "4.4 lbs, Milk Chocolate",
    img: "images/products/product6.png",
  },
  {
    id: "thierytbvcbvzdhadjk",
    name: "Muscle Blaze Super Gainer",
    price: 5699,
    desc: "4.4 lbs, Cookies and Cream",
    img: "images/products/product7.png",
  },
  {
    id: "trfoiwfcnbcawdjksadjk",
    name: "MB Creatinine Capsules",
    price: 1599,
    desc: "Suitable for Vegeterian, 90 soft gells",
    img: "images/products/product8.png",
  },
  {
    id: "cbvxbcvsceldk",
    name: "Cellucor C4 Pre-Workout Supplements",
    price: 1399,
    desc: "Suitable for Vegeterian, 90 soft gells",
    img: "images/products/product9.png",
  },
  {
    id: "oiopijmjkhuihb",
    name: "Proquest Raw Whey Protein",
    price: 5990,
    desc: " 4 kg (8.8 lb)",
    img: "images/products/product10.png",
  },
  {
    id: "oiopijewyiohbjhib",
    name: "MuscleBlaze High Protein Peanut Butter",
    price: 629,
    desc: "1 kg, Dark Chocolate Creamy",
    img: "images/products/product11.png",
  },
  {
    id: "rtytytuyuytyytbvncv",
    name: "Wow Life Science Testoboost",
    price: 350,
    desc: "Testosterone Booster, 60 veggie capsule(s)",
    img: "images/products/product12.png",
  },
  {
    id: "rtytytuyuytyytbvncv",
    name: "MuscleBlaze Biozyme Daily Multivitamin",
    price: 999,
    desc: "90 tablet(s)",
    img: "images/products/product13.png",
  },
  {
    id: "rtytytuyuytyytbvncv",
    name: "HealthKart HK Vitals Biotin",
    price: 499,
    desc: "(10000 mcg), 90 tablet(s)",
    img: "images/products/product14.png",
  },
  {
    id: "rtytytuyuytyytbvncv",
    name: "Scivation Xtend BCAA (Intra Workout Catalyst)",
    price: 2739,
    desc: "30 Servings, 410 g (0.9 lb), Blue Raspberry Ice",
    img: "images/products/product15.png",
  },
  
];

